### ISSUE TITLE
Conection problem

### ISSUE THREAD

**Issue by nolimitek** [aloishockenschlohe/dpm86_power_supply#2]
Hi 

I own a dpm8624. Tested it with the windows pogram and from  joy it and the communication works
If i test it with your program i get
./dpm86 output on
./dpm86: line 32: ./basic-functions: No such file or directory
./dpm86: line 158: slog: command not found
./dpm86: line 169: slog: command not found
./dpm86: line 173: slog: command not found
ERROR -- Communication with dpm86 failed: Timeout reading response.

basic_functions is in the same directory

any ideas ?

thx
regards Chris

**Comment by aloishockenschlohe** [comment]
Hi!

Thanks for your mail.
It seems as if you forgot to place the file 'basic-functions' in the same directory as the file dpm86.

Please place both files in the same directory, change into this directory and start the dpm86.

Have fun!

Alois

**Comment by aloishockenschlohe** [comment]
I close your issue until further problems. :-)

**Comment by aloishockenschlohe** [comment]
Hi!

I was much too fast... Sorry...
Here the new answer:

a) Please check if the file 'basic_functions' is executable. If not, please make it executable via 'chmod +x ./basic-functions'.
b) Please check what device is used by the dpm8624. This depends on your hardware configuration. It should be something like '/dev/ttyUSB0' or '/dev/ttyUSB1'. Please be sure that the entry in line 48 of 'dpm86' is corresponds with the device used in your setup.
c) Last idea: Please check if the device ID of your dpm8624 corresponds with the entry in line 47 of 'dpm86'. The ID is '01' by default. Unless you changed the setup of your dpm8624 it should match.

Greetings!

**Comment by stcan** [comment]
Hi,

Unfortunately, I have the same problem. The error message is exactly the same, although the settings (a,b,c) are all correct.

I am using a DPM8624-485 with the included RS485-USB adapter and a Raspberry PI with current "Raspbian GNU/Linux 11 (bullseye)".

Thanks in advance.
steve

**Comment by stcan** [comment]
Problem solved:
The filename is ./basic_functions  and this is not the same name as in the source command

./dpm86 Line 32:
. ./basic-functions     # please be sure, that this file is placed in the same directory and is executable

Solution: Either rename the file or change the source command ... 

Best,
steve

**Comment by aloishockenschlohe** [comment]
Thanks! Fixed it.
Please gimme feedback if it works now.

**Comment by stcan** [comment]
It runs perfectly! Thanks for the good work.
steve

**Comment by aloishockenschlohe** [comment]
Happy to hear! :-)
Issue closed.
