### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ederpatrick** [aloishockenschlohe/dpm86_power_supply#4]
Hello,  i want to say thanks for the good Job!! 

And i was wondering isnt it possibe to get this into mqtt or simmilar somehow?

I assume we have the same plan for a PV system, but saddly for me , you use a differend hardware.

-i use
-Home Assistant
-hoymiles hm1500 micro inverter with open dtu (esp32)
-7KWH LiIon Battery from VW ID3 (blckBMS)
-dpm8650 RS485 1300W dcdc converter
-shelly 3em 

Everything except the DPM is up in homeassistant and i get all the data from the devices and would be able to calculate the actual needed power and it would be cool now to make some kind of 0 overflow controle via home assistant but only in the power area >300W  <500W which runs 24/7  sourced by battery.. that should safe a lot of money. 300W 24/7 and in case the Sun is shinning very strong and the AC side is using a lot of Power, the inverter should receive lets say 1000W by the DC Converter.

Do you think your code is adjustable to be able to get this values somehow into HA? Maybe with or without raspi.

Hope for Input
A lot of Regards from the Alps

**Comment by aloishockenschlohe** [comment]
Hi!

This repository contains just a command-line tool for controlling the dpm86 power supply.

The latest version of the tool is object-orientated and quite well documented. It can be easily modified.

Unfortunately I don't have the time to write a wrapper for any kind of home automation environment. :-(
But feel free to modify the code. :-)

ps:
The repository https://github.com/aloishockenschlohe/diy-smart-solarplant will be updated soon.
Also completely object-orientated in python.

**Comment by ederpatrick** [comment]
Thanks for the permission, i'll try to ;-)
Looking forward to get updates in your projects.

Regards

**Comment by aloishockenschlohe** [comment]
Closing this issue.
