### ISSUE TITLE
Current is out of range for values higher than '9'

### ISSUE THREAD

**Issue by BerziOnline** [aloishockenschlohe/dpm86_power_supply#5]
Hey, thanks a lot for this amazing script!

Just one issue I am facing with a DPM8624-485:

> pi@raspberrypi-solar:~ $ dpm86 a max
24.0
pi@raspberrypi-solar:~ $ dpm86 a 10
ERROR: Value for current is out of range.
pi@raspberrypi-solar:~ $ dpm86 a 9
ok

I cannot set a higher value than 9 for the current. The voltage is fine and is settable in the full range. For the current I can just set values between 0-9. 

Thanks a lot!

Regards
BerziOnline

**Comment by aloishockenschlohe** [comment]
Hi!

Please open the script in an editor and change the variable "CURRENT_MAX" in line 80 to the maximum current of your device.

Feel free to implement a routine to set this variable automatically depending on the detected device. :-)

Many greetings


Alois
